title: Cyberarm
email: cyberarm@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _cyberarm
github_username:  cyberarm

# Build settings
plugins:
  - jekyll-feed

# SASS
sass:
  sass_dir: _sass
  style: compact

theme:

permalink: /blog/:year/:month/:day/:title/